force-app/main/default/objects/Product_Review__c/Product_Review__c.object-meta.xml
<CustomObject>
    <label>Product Review</label>
    <nameField>
        <label>Product Reviews Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Review__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Reviews</relationshipLabel>
    <relationshipName>Product_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Review__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <label>Review</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CommentsController.cls
public with sharing class CommentsController {

    @AuraEnabled(cacheable=true scope='global')
    public static Product_Review__c[] getComments(String productId){
        return [
            SELECT Id, Review__c,  Product__r.Name
            FROM Product_Review__c WHERE Product__c =: productId
            ORDER BY CreatedDate DESC
            LIMIT 5
        ];
    }

    @AuraEnabled(cacheable=true scope='global')
    public static Product_Review__c[] getAllComments(String productId){
        return [
            SELECT Id, Review__c,  Product__r.Name
            FROM Product_Review__c WHERE Product__c =: productId
            ORDER BY CreatedDate DESC
        ];
    }
}